### ISSUE TITLE
Data Request

### ISSUE THREAD

**Issue by Zhklu2003** [shadowdeng1994/TacCA_sourcedata#1]
Hi Dr. Deng,

Could you also upload the data for biasgenes_inf <- read.csv(file='~/.../bias_gene.csv',header=T) in this AnalysisOfStaticCellBarcodingData.R file? 

Thanks!

**Comment by shadowdeng1994** [comment]
Hi, 

Thank you for your interest in our work. The requested dataset is now available in CoSpar/bias_gene.csv. Let me know if you need any further assistent. 

Yours,
Shanjun

**Comment by Zhklu2003** [comment]
Thanks for replying me!

Could you also upload the data for hematopoiesis csv? I have tried the data in the CoSpar document, but it seems that it will take too long time for the whole program. 

Besides, some of the clones may have only one cell, which makes the choose(1,2) problematic. How did you deal with this issue? 

Thanks!

**Comment by shadowdeng1994** [comment]
Hi,

We did not retain the public data locally, so you may need to obtain these files by following the tutorial provided by Cospar. 

Additionally, for clades or clones containing only a single cell (also known as singletons), no coalescent event can be observed. This corresponds to the fact that the combination C(1,2)=0.

Yours,
Shanjun
